#!/usr/bin/env python3
"""
viSales CRM Reminder — ICS Generator
Generates .ics calendar files with structured CRM data in the description.
"""

import argparse
import re
import uuid
from datetime import datetime, timedelta
from pathlib import Path


def sanitize_filename(name: str) -> str:
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[\s]+', '-', name.strip())
    return name


def escape_ics_text(text: str) -> str:
    text = text.replace('\\', '\\\\')
    text = text.replace(';', '\\;')
    text = text.replace(',', '\\,')
    text = text.replace('\n', '\\n')
    return text


def priority_display(prio: str) -> str:
    mapping = {'hoch': '⚡ HOCH', 'mittel': '● MITTEL', 'niedrig': '○ NIEDRIG'}
    return mapping.get(prio.lower(), f'● {prio.upper()}')


def priority_ics_value(prio: str) -> str:
    mapping = {'hoch': '1', 'mittel': '5', 'niedrig': '9'}
    return mapping.get(prio.lower(), '5')


def build_description(args) -> str:
    lines = []
    lines.append('═══ viSales CRM Reminder ═══')
    lines.append('')
    lines.append('📋 KUNDE')
    lines.append(f'Firma: {args.firma}')
    if args.ansprechpartner:
        lines.append(f'Ansprechpartner: {args.ansprechpartner}')
    if args.telefon:
        lines.append(f'Tel: {args.telefon}')
    if args.email:
        lines.append(f'Mail: {args.email}')
    lines.append('')
    if args.thema or args.prioritaet:
        lines.append('🎯 ANLASS')
        if args.thema:
            lines.append(f'Thema: {args.thema}')
        lines.append(f'Priorität: {priority_display(args.prioritaet)}')
        lines.append('')
    has_deal_info = any([args.deal_phase, args.budget, args.letzte_interaktion])
    if has_deal_info:
        lines.append('📊 DEAL STATUS')
        if args.deal_phase:
            lines.append(f'Phase: {args.deal_phase}')
        if args.budget:
            lines.append(f'Budget: {args.budget}')
        if args.letzte_interaktion:
            lines.append(f'Letzte Interaktion: {args.letzte_interaktion}')
        lines.append('')
    if args.naechster_schritt:
        lines.append('➡️ NÄCHSTER SCHRITT')
        lines.append(args.naechster_schritt)
        lines.append('')
    if args.notizen:
        lines.append('📝 NOTIZEN')
        lines.append(args.notizen)
        lines.append('')
    lines.append('───')
    lines.append('Generated by viSales CRM Reminder')
    return '\n'.join(lines)


def build_summary(args) -> str:
    parts = [f'📞 {args.firma}']
    if args.ansprechpartner:
        parts.append(f'({args.ansprechpartner})')
    if args.thema:
        parts.append(f'— {args.thema}')
    return ' '.join(parts)


def generate_ics(args) -> str:
    dt_start = datetime.strptime(f'{args.datum} {args.uhrzeit}', '%Y-%m-%d %H:%M')
    dt_end = dt_start + timedelta(minutes=args.dauer)
    fmt = '%Y%m%dT%H%M%S'
    dtstart = dt_start.strftime(fmt)
    dtend = dt_end.strftime(fmt)
    dtstamp = datetime.utcnow().strftime(fmt) + 'Z'
    uid = str(uuid.uuid4())
    summary = build_summary(args)
    description = build_description(args)
    desc_escaped = escape_ics_text(description)
    ics_lines = [
        'BEGIN:VCALENDAR', 'VERSION:2.0',
        'PRODID:-//viSales GmbH//CRM Reminder//DE',
        'CALSCALE:GREGORIAN', 'METHOD:PUBLISH', 'BEGIN:VEVENT',
        f'UID:{uid}', f'DTSTAMP:{dtstamp}',
        f'DTSTART:{dtstart}', f'DTEND:{dtend}',
        f'SUMMARY:{escape_ics_text(summary)}',
        f'DESCRIPTION:{desc_escaped}',
        f'PRIORITY:{priority_ics_value(args.prioritaet)}',
        'STATUS:CONFIRMED', 'TRANSP:OPAQUE',
    ]
    if args.alarm > 0:
        ics_lines.extend([
            'BEGIN:VALARM', f'TRIGGER:-PT{args.alarm}M',
            'ACTION:DISPLAY',
            f'DESCRIPTION:Reminder: {args.firma} kontaktieren',
            'END:VALARM',
        ])
    categories = ['viSales CRM']
    if args.deal_phase:
        categories.append(args.deal_phase)
    if args.prioritaet.lower() == 'hoch':
        categories.append('Priorität Hoch')
    ics_lines.append(f'CATEGORIES:{",".join(categories)}')
    ics_lines.extend(['END:VEVENT', 'END:VCALENDAR'])
    return '\r\n'.join(ics_lines)


def main():
    parser = argparse.ArgumentParser(description='viSales CRM Reminder ICS Generator')
    parser.add_argument('--firma', required=True)
    parser.add_argument('--datum', required=True)
    parser.add_argument('--uhrzeit', required=True)
    parser.add_argument('--ansprechpartner', default='')
    parser.add_argument('--telefon', default='')
    parser.add_argument('--email', default='')
    parser.add_argument('--thema', default='')
    parser.add_argument('--prioritaet', default='mittel')
    parser.add_argument('--letzte-interaktion', dest='letzte_interaktion', default='')
    parser.add_argument('--deal-phase', dest='deal_phase', default='')
    parser.add_argument('--budget', default='')
    parser.add_argument('--naechster-schritt', dest='naechster_schritt', default='')
    parser.add_argument('--notizen', default='')
    parser.add_argument('--dauer', type=int, default=30)
    parser.add_argument('--alarm', type=int, default=15)
    parser.add_argument('--output', required=True)
    args = parser.parse_args()
    ics_content = generate_ics(args)
    output_path = Path(args.output)
    if output_path.is_dir() or not output_path.suffix:
        filename = f'{args.datum}_{sanitize_filename(args.firma)}_Reminder.ics'
        output_path = output_path / filename
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(ics_content, encoding='utf-8')
    print(f'✅ ICS-Datei erstellt: {output_path}')


if __name__ == '__main__':
    main()
